# more info: https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - init: npm install
    command: |
      expot HMR_HOST=`gp url 300`
      npm run dev -- --open

# ports:
#   - port: 3000
#     onOpen: open-browser
 
vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true